# Generated by Django 4.2.3 on 2023-07-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
